# Generated by Django 2.2.4 on 2019-09-08 21:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('administrator', 'administrator'), ('subscriber', 'subscriber')], default='subscriber', max_length=50)),
                ('categories', models.ManyToManyField(blank=True, to='ebook_repository.Category')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.IntegerField(blank=True)),
                ('filename', models.FileField(blank=True, upload_to='uploads/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ebook_repository.Category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ebook_repository.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook_repository.User')),
            ],
        ),
    ]
